<?xml version="1.0" ?>
<!-- 
	The dictionary key is used in the system to get a handle to the type 
	of dictionary (see DictionaryManager for more information).
	The version node key is used in the caching and per-project settings.
	
	When CFE starts it will load up the first version in each dictionary.
	If another project is then created (or switched to) then any other
	needed dictionaries will be loaded and cached. So, if you put the one 
	you use	most at the top you'll gain a touch of speed.
	
	Also note at present you will only get one SQL file grammar / version
	no matter how many CF version you are using. Meaning it is not 
	possible to configure cfmx701 with SQL Server *and* bd61 with MYSQL 
	server grammar at the same time.
-->
<!DOCTYPE dictionary_config [
	<!ELEMENT dictionary_config (dictionary+)>
	<!ELEMENT dictionary (version+)>
	<!ATTLIST dictionary
		id ID #REQUIRED
	>
	<!ELEMENT version (grammar+)>
	<!ATTLIST version
		key ID #REQUIRED
		label CDATA #REQUIRED
	>
	<!ELEMENT grammar EMPTY>
	<!ATTLIST grammar
		location CDATA #REQUIRED
	>
]>
<dictionary_config>
	<dictionary id="CF_DICTIONARY">
		<version key="awesomedic" label="Wroxin 3 3s">
			<grammar location="awesomedic.xml" />
		</version>
	</dictionary>

	<dictionary id="JS_DICTIONARY">
		<version key="ecma" label="ECMA Javascript">
			<grammar location="js.xml" />
		</version>
	</dictionary>

	<dictionary id="REMOTE_DICT">
		<version key="ecma" label="Remote dictionary for testing">
			<grammar location="file:///Users/valliant/Projects/java/CFML/cfml.dictionary/test/data/dictionary/js.xml" />
		</version>
	</dictionary>

	<!-- note that this will get loaded into the CFML dictionary -->
	<dictionary id="SQL_DICTIONARY">
		<version key="mssql" label="Microsoft(R) SQL Server">
			<grammar location="sqlkeywords.txt" />
		</version>
	</dictionary>
	
	<dictionary id="HT_DICTIONARY">
		<version key="xhtml" label="XHTML">
			<grammar location="html.xml" />
		</version>
	</dictionary>
	
</dictionary_config>