=== cflint/CFLint/Dictionary/src/main/resources/dictionary/compatibility.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
	targetNamespace="http://www.cfeclipse.org/version1/dictionary"
	xmlns="http://www.cfeclipse.org/version1/dictionary http://cfeclipse.tigris.org/version1/dictionary/compatibility.xsd"
>
	<!-- root element -->
	<xs:element name="compatibilities">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="compatibility" minOccurs="1" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="compatibility">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="tags" minOccurs="0" maxOccurs="1" />
				<xs:element ref="functions" minOccurs="0" maxOccurs="1" />
				<xs:element ref="scopes" minOccurs="0" maxOccurs="1" />
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required" />
			<xs:attribute name="version" type="xs:integer" use="required" />
			<xs:attribute name="previous" type="xs:integer" use="optional" />
		</xs:complexType>
	</xs:element>
	
	<!-- second level elements (main groups) -->
	<xs:element name="tags" type="change_type" />
	<xs:element name="functions" type="change_type" />
	<xs:element name="scopes" type="change_type" />
	
	<xs:complexType name="change_type">
		<xs:sequence>
			<xs:element ref="new" minOccurs="0" maxOccurs="unbounded" />
			<xs:element ref="changed" minOccurs="0" maxOccurs="unbounded" />
			<xs:element ref="deprecated" minOccurs="0" maxOccurs="unbounded" />
			<xs:element ref="obsolete" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:element name="new" type="compat_type" />
	<xs:element name="changed" type="compat_type" />
	<xs:element name="deprecated" type="compat_type" />
	<xs:element name="obsolete" type="compat_type" />
	
	<xs:complexType name="compat_type">
		<xs:sequence>
			<xs:element ref="help" />
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required" />
		<xs:attribute name="type" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="all" />
					<xs:enumeration value="parameter" />
					<xs:enumeration value="value" />
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="parameter" type="xs:string" use="optional" />
		<xs:attribute name="value" type="xs:string" use="optional" />
		<xs:attribute name="index" type="xs:integer" use="optional" />
	</xs:complexType>
	
	<xs:element name="help" type="xs:string" />
	
</xs:schema>

=== cflint/CFLint/Dictionary/src/main/resources/dictionary/compatibility.xml
<?xml version="1.0" ?>
<compatibilities xmlns="http://www.cfeclipse.org/version1/dictionary"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.cfeclipse.org/version1/dictionary http://cfeclipse.tigris.org/version1/dictionary/compatibility.xsd"
>
	<compatibility name="ColdFusion Server" version="7" previous="6.1">
		<tags>
			<new name="cfapplication" type="parameter" parameter="scriptprotect"><help><![CDATA[  ]]></help></new>
			<new name="cfargument" type="value" parameter="type" value="xml"><help><![CDATA[  ]]></help></new>
			<new name="cfcalendar" type="all"><help><![CDATA[  ]]></help></new>
			<new name="cfchart" type="parameter" parameter="style"><help><![CDATA[  ]]></help></new>
			<new name="cfchart" type="parameter" parameter="title"><help><![CDATA[  ]]></help></new>
			<new name="cfchartseries" type="parameter" parameter="datalabelstyle"><help><![CDATA[  ]]></help></new>
			<new name="cfchartseries" type="value" parameter="type" value="horizontalbar"><help><![CDATA[  ]]></help></new>
			<new name="cfcollection" type="parameter" parameter="categories"><help><![CDATA[  ]]></help></new>
			<new name="cfcollection" type="value" parameter="language" value="*"><help><![CDATA[  ]]></help></new>
			<new name="cfcomponent" type="parameter" parameter="style"><help><![CDATA[  ]]></help></new>
			<new name="cfcomponent" type="parameter" parameter="namespace"><help><![CDATA[  ]]></help></new>
			<new name="cfcomponent" type="parameter" parameter="serviceportname"><help><![CDATA[  ]]></help></new>
			<new name="cfcomponent" type="parameter" parameter="porttypename"><help><![CDATA[  ]]></help></new>
			<new name="cfcomponent" type="parameter" parameter="wsdlfile"><help><![CDATA[  ]]></help></new>
			<new name="cfcomponent" type="parameter" parameter="bindingname"><help><![CDATA[  ]]></help></new>
			<new name="cfcontent" type="parameter" parameter="variable"><help><![CDATA[  ]]></help></new>
			<new name="cfdirectory" type="parameter" parameter="recurse"><help><![CDATA[  ]]></help></new>
			<new name="cfdocument" type="all"><help><![CDATA[  ]]></help></new>
			<new name="cfdocumentitem" type="all"><help><![CDATA[  ]]></help></new>
			<new name="cfdocumentsection" type="all"><help><![CDATA[  ]]></help></new>
			<new name="cffile" type="parameter" parameter="result"><help><![CDATA[  ]]></help></new>
			<new name="cffile" type="parameter" parameter="fixnewline"><help><![CDATA[  ]]></help></new>
			<changed name="cfform" type="parameter" parameter="name"><help><![CDATA[  ]]></help></changed>
			<changed name="cfform" type="parameter" parameter="action"><help><![CDATA[  ]]></help></changed>
			<new name="cfform" type="parameter" parameter="accessible"><help><![CDATA[  ]]></help></new>
			<new name="cfform" type="parameter" parameter="format"><help><![CDATA[  ]]></help></new>
			<new name="cfform" type="parameter" parameter="height"><help><![CDATA[  ]]></help></new>
			<new name="cfform" type="parameter" parameter="width"><help><![CDATA[  ]]></help></new>
			<new name="cfform" type="parameter" parameter="method"><help><![CDATA[  ]]></help></new>
			<new name="cfform" type="parameter" parameter="onerror"><help><![CDATA[  ]]></help></new>
			<new name="cfform" type="parameter" parameter="preloader"><help><![CDATA[  ]]></help></new>
			<new name="cfform" type="parameter" parameter="scriptsrc"><help><![CDATA[  ]]></help></new>
			<new name="cfform" type="parameter" parameter="skin"><help><![CDATA[  ]]></help></new>
			<new name="cfform" type="parameter" parameter="style"><help><![CDATA[  ]]></help></new>
			<new name="cfform" type="parameter" parameter="timeout"><help><![CDATA[  ]]></help></new>
			<new name="cfform" type="parameter" parameter="wmode"><help><![CDATA[  ]]></help></new>
			<new name="cfform" type="parameter" parameter="onreset"><help><![CDATA[  ]]></help></new>
			<new name="cfformgroup" type="all"><help><![CDATA[  ]]></help></new>
			<new name="cfformitem" type="all"><help><![CDATA[  ]]></help></new>
			<new name="cfftp" type="parameter" parameter="result"><help><![CDATA[  ]]></help></new>
			<new name="cffunction" type="parameter" parameter="description"><help><![CDATA[  ]]></help></new>
			<new name="cffunction" type="value" parameter="returntype" value="xml"><help><![CDATA[  ]]></help></new>
			<new name="cfgrid" type="parameter" parameter="format"><help><![CDATA[  ]]></help></new>
			<new name="cfgrid" type="parameter" parameter="enabled"><help><![CDATA[  ]]></help></new>
			<new name="cfgrid" type="parameter" parameter="onchange"><help><![CDATA[  ]]></help></new>
			<new name="cfgrid" type="parameter" parameter="style"><help><![CDATA[  ]]></help></new>
			<new name="cfgrid" type="parameter" parameter="tooltip"><help><![CDATA[  ]]></help></new>
			<new name="cfgrid" type="parameter" parameter="visible"><help><![CDATA[  ]]></help></new>
			<new name="cfgridcolumn" type="parameter" parameter="mask"><help><![CDATA[  ]]></help></new>
			<new name="cfgridcolumn" type="value" parameter="type" value="currency"><help><![CDATA[  ]]></help></new>
			<new name="cfindex" type="parameter" parameter="custom2"><help><![CDATA[  ]]></help></new>
			<new name="cfindex" type="parameter" parameter="custom3"><help><![CDATA[  ]]></help></new>
			<new name="cfindex" type="parameter" parameter="category"><help><![CDATA[  ]]></help></new>
			<new name="cfindex" type="parameter" parameter="categorytree"><help><![CDATA[  ]]></help></new>
			<new name="cfindex" type="parameter" parameter="status"><help><![CDATA[  ]]></help></new>
			<new name="cfindex" type="value" parameter="language" value="*"><help><![CDATA[  ]]></help></new>
			<new name="cfinput" type="parameter" parameter="height"><help><![CDATA[  ]]></help></new>
			<new name="cfinput" type="parameter" parameter="width"><help><![CDATA[  ]]></help></new>
			<new name="cfinput" type="parameter" parameter="bind"><help><![CDATA[  ]]></help></new>
			<new name="cfinput" type="parameter" parameter="label"><help><![CDATA[  ]]></help></new>
			<new name="cfinput" type="parameter" parameter="mask"><help><![CDATA[  ]]></help></new>
			<new name="cfinput" type="parameter" parameter="validateat"><help><![CDATA[  ]]></help></new>
			<new name="cfinput" type="parameter" parameter="daynames"><help><![CDATA[  ]]></help></new>
			<new name="cfinput" type="parameter" parameter="monthnames"><help><![CDATA[  ]]></help></new>
			<new name="cfinput" type="parameter" parameter="tooltip"><help><![CDATA[  ]]></help></new>
			<new name="cfinput" type="parameter" parameter="visible"><help><![CDATA[  ]]></help></new>
			<new name="cfinput" type="parameter" parameter="enabled"><help><![CDATA[  ]]></help></new>
			<new name="cfinput" type="parameter" parameter="src"><help><![CDATA[  ]]></help></new>
			<new name="cfinput" type="value" parameter="type" value="datefield"><help><![CDATA[  ]]></help></new>
			<new name="cfinput" type="value" parameter="type" value="button"><help><![CDATA[  ]]></help></new>
			<new name="cfinput" type="value" parameter="type" value="file"><help><![CDATA[  ]]></help></new>
			<new name="cfinput" type="value" parameter="type" value="hidden"><help><![CDATA[  ]]></help></new>
			<new name="cfinput" type="value" parameter="type" value="image"><help><![CDATA[  ]]></help></new>
			<new name="cfinput" type="value" parameter="type" value="reset"><help><![CDATA[  ]]></help></new>
			<new name="cfinput" type="value" parameter="type" value="submit"><help><![CDATA[  ]]></help></new>
			<new name="cfinput" type="value" parameter="validate" value="boolean"><help><![CDATA[  ]]></help></new>
			<new name="cfinput" type="value" parameter="validate" value="email"><help><![CDATA[  ]]></help></new>
			<new name="cfinput" type="value" parameter="validate" value="guid"><help><![CDATA[  ]]></help></new>
			<new name="cfinput" type="value" parameter="validate" value="maxlength"><help><![CDATA[  ]]></help></new>
			<new name="cfinput" type="value" parameter="validate" value="noblanks"><help><![CDATA[  ]]></help></new>
			<new name="cfinput" type="value" parameter="validate" value="range"><help><![CDATA[  ]]></help></new>
			<new name="cfinput" type="value" parameter="validate" value="submitonce"><help><![CDATA[  ]]></help></new>
			<new name="cfinput" type="value" parameter="validate" value="url"><help><![CDATA[  ]]></help></new>
			<new name="cfinput" type="value" parameter="validate" value="usdate"><help><![CDATA[  ]]></help></new>
			<new name="cfinput" type="value" parameter="validate" value="uuid"><help><![CDATA[  ]]></help></new>
			<new name="cfinvoke" type="parameter" parameter="serviceport"><help><![CDATA[  ]]></help></new>
			<new name="cfinvokeargument" type="parameter" parameter="omit"><help><![CDATA[  ]]></help></new>
			<new name="cfldap" type="parameter" parameter="returnasbinary"><help><![CDATA[  ]]></help></new>
			<new name="cfmailparam" type="parameter" parameter="contentid"><help><![CDATA[  ]]></help></new>
			<new name="cfmailparam" type="parameter" parameter="dispositionattributes"><help><![CDATA[  ]]></help></new>
			<new name="cfntauthenticate" type="all"><help><![CDATA[  ]]></help></new>
			<new name="cfparam" type="parameter" parameter="min"><help><![CDATA[  ]]></help></new>
			<new name="cfparam" type="parameter" parameter="max"><help><![CDATA[  ]]></help></new>
			<new name="cfparam" type="parameter" parameter="pattern"><help><![CDATA[  ]]></help></new>
			<new name="cfparam" type="value" parameter="type" value="creditcard"><help><![CDATA[  ]]></help></new>
			<new name="cfparam" type="value" parameter="type" value="email"><help><![CDATA[  ]]></help></new>
			<new name="cfparam" type="value" parameter="type" value="eurodate"><help><![CDATA[  ]]></help></new>
			<new name="cfparam" type="value" parameter="type" value="float"><help><![CDATA[  ]]></help></new>
			<new name="cfparam" type="value" parameter="type" value="integer"><help><![CDATA[  ]]></help></new>
